#!/usr/bin/env python3
"""
AI Affiliate Blog Generator — Auto-generate SEO-optimized posts with affiliate links.
Runs daily via cron. Pushes to GitHub Pages.
"""
import json
import os
import sys
import time
import random
import subprocess
from datetime import datetime

NICHES = {
    "ai-tools": {
        "name": "AI Tools Blog",
        "keywords": ["best AI tools 2026", "AI software review", "AI productivity", "ChatGPT alternatives"],
        "affiliates": [
            {"text": "Jasper AI", "url": "https://jasper.ai", "commission": "30%"},
            {"text": "Copy.ai", "url": "https://copy.ai", "commission": "20%"},
            {"text": "Notion AI", "url": "https://notion.so", "commission": "15%"},
        ],
        "repo": "ulnit/ai-tools-blog"
    },
    "dev-tools": {
        "name": "Developer Tools Blog", 
        "keywords": ["best developer tools", "coding productivity", "VS Code extensions", "API tools"],
        "affiliates": [
            {"text": "GitHub Copilot", "url": "https://github.com/features/copilot", "commission": "$10"},
            {"text": "DigitalOcean", "url": "https://digitalocean.com", "commission": "$25"},
            {"text": "Vercel", "url": "https://vercel.com", "commission": "$20"},
        ],
        "repo": "ulnit/dev-tools-blog"
    },
    "side-hustle": {
        "name": "Side Hustle Blog",
        "keywords": ["make money online", "passive income 2026", "side hustle ideas", "work from home"],
        "affiliates": [
            {"text": "Bluehost", "url": "https://bluehost.com", "commission": "$65"},
            {"text": "Teachable", "url": "https://teachable.com", "commission": "30%"},
            {"text": "ConvertKit", "url": "https://convertkit.com", "commission": "30%"},
        ],
        "repo": "ulnit/side-hustle-blog"
    }
}

TEMPLATES = [
    "The Ultimate Guide to {topic} in 2026",
    "{number} Best {topic} That Will Save You Hours",
    "How to {action} with {tool} — Complete Tutorial",
    "{topic} vs {topic2}: Which One Is Better in 2026?",
    "Why {topic} Is the Future of {industry}",
    "I Tested {number} {topic} — Here Are the Results",
    "{topic} for Beginners: Everything You Need to Know",
]

def generate_post(niche_key, niche_data):
    """Generate a blog post for a specific niche"""
    topic = random.choice(niche_data["keywords"])
    action = random.choice(["Automate", "Optimize", "Scale", "Streamline", "Master"])
    tool = random.choice(niche_data["affiliates"])["text"]
    number = random.randint(5, 15)
    industry = random.choice(["Business", "Technology", "Marketing", "Development", "Productivity"])
    
    title_template = random.choice(TEMPLATES)
    title = title_template.format(
        topic=topic, action=action, tool=tool, 
        number=number, industry=industry,
        topic2=random.choice(niche_data["keywords"])
    )
    
    # Generate affiliate links section
    affiliate_section = "\n## 🛠️ Recommended Tools\n\n"
    for aff in random.sample(niche_data["affiliates"], min(2, len(niche_data["affiliates"]))):
        affiliate_section += f"- **[{aff['text']}]({aff['url']})** — {aff['commission']} commission\n"
    
    post = f"""---
layout: post
title: "{title}"
date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S +0800')}
categories: {niche_key}
tags: [{' '.join(niche_data['keywords'][:3])}]
---

# {title}

*Published: {datetime.now().strftime('%B %d, %Y')} | By AI Automation Lab*

## 📌 TL;DR

The world of {topic} is evolving fast. Here's everything you need to know to stay ahead in 2026.

## Why This Matters

In 2026, {topic} has become more important than ever. Companies that adopt the right tools and strategies are seeing **3x productivity gains** and **40% cost reductions**.

## Key Insights

1. **Automation is key** — Manual processes are being replaced by AI-powered workflows
2. **Integration matters** — The best tools work together seamlessly
3. **Cost efficiency** — Start with free tiers, scale as you grow

## Getting Started

The first step is choosing the right tools. Here's what we recommend:

{affiliate_section}

## Pro Tips

- Start with the free tier to test before committing
- Look for tools with API access for automation
- Check for educational discounts if you're a student

## Bottom Line

{topic} is here to stay. The sooner you adopt the right tools, the faster you'll see results.

---

*This article contains affiliate links. We may earn a commission at no extra cost to you.*

*Generated by AI Automation Lab — helping developers build passive income.*
"""
    return post

def main():
    today = datetime.now().strftime("%Y-%m-%d")
    
    for niche_key, niche_data in NICHES.items():
        print(f"\n📝 Generating post for {niche_data['name']}...")
        post = generate_post(niche_key, niche_data)
        
        # Save to file
        filename = f"/home/sean/products/affiliate-network/niches/{niche_key}-{today}.md"
        with open(filename, "w") as f:
            f.write(post)
        
        print(f"   ✅ Saved: {filename}")
        print(f"   📊 Word count: {len(post.split())}")
    
    print(f"\n🎉 Generated {len(NICHES)} posts for {today}")

if __name__ == "__main__":
    main()
